# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema necesarias para Python packages
RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend /app

# Comando de inicio (usando Uvicorn)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]